# 넘파이(Numpy)
    - 파이썬을 활용한 데이터 분석에서 가장 기본이 되는 라이브러리
    - 넘파이로만으로도 많이 사용되지만, 판다스(pandas), 머신러닝 들 수많은 분야에서   
    기본적으로 사용되므로 파이썬 개발자의 필수 라이브러리이다.

[넘파이 공식 문서](https://numpy.org/)

### 1) 수학 수치연산(numerical python)
    - 합, 평균, 행렬연산 등이 가능하다
### 2) 기본 타입
    - ndarray (n-dimenstional array) 다차원 배열의 표현
### 3) 파이썬 list가 있음에도 필요한 이유
    - 성능 : 성능적으로 훨씬 빠르다
    - 메모리 : 적은 메모리를 사용한다
    - 제공함수 : 선형대수, 통계관련 여러 수치 함수를 제공한다
    - 그 외 수 많은 모듈에서 numpy 함수명과 기능을 그대로 사용 가능하다

<img src="https://media.licdn.com/dms/image/v2/D4E22AQFKQ93ywmSGsg/feedshare-shrink_800/B4EZ.vxZJAHoAg-/0/1785360388974?e=2147483647&v=beta&t=qutjb0gyTs5FKZTWL_mxm1Xd_q22lPtZFuOiM5EAb5U" width="800"/>

In [4]:
import numpy as np


In [6]:
# arr1 = np.ndarray([1, 2, 3])
arr1 = np.array([1, 2, 3])

print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
# 하나의 타입으로만 정의할 수 있다 
arr2 = np.array([      1,2,3.0])
print(arr2)
print(arr2)
print([1,2,3.0])
arr2

[1. 2. 3.]
[1. 2. 3.]
[1, 2, 3.0]


array([1., 2., 3.])

In [10]:
# 넘파이의 타입 강제 승격
arr3 = np.array([1, 2, False, "홍길동", 12.5])

print(arr3)
print(type(arr3))

['1' '2' 'False' '홍길동' '12.5']
<class 'numpy.ndarray'>


In [11]:
arr3 = np.array([i + 1 for i in range(10)])

arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# ndarray의 인덱싱

In [15]:
print(arr3)
print(type(arr3[1]))
print(int(arr3[1]))

print(2)
print(type(1))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.int64'>
2
2
<class 'int'>


## ndarray의 슬라이싱 

In [21]:
print(arr3)
print(arr3[2:5])
print(arr3[::2])

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5]
[1 3 5 7 9]


### shape
    - numpy에서는 해당 array의 크기를 알 수 있다. shape를 확인함으로서, 몇 개의 데이터가 있는지 몇 차원으로 존재하는지 확인할 수 있다.
    - arr.shape의 결과는 튜플로 (행, 열)로 행만 존재하면 1차원, 행렬이 존재하면 2차원으로 차수를 알 수 있다. 또한 행*렬을 곱하면 크기도 확인할 수 있다.

In [22]:
arr3.shape
# 1차원 (10,)
# 1차원 , goddml 10ro epdlxj

# 1차원 벡터 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr4 = np.array([[2]]) 
arr4

array([[2]])

In [24]:
# 2차원 스칼라
print(arr4)
print(arr4. shape)
    # 스칼라 [[]] = 2차원 , 2 = 문자 하나라서 스칼라

[[2]]
(1, 1)


In [26]:
arr5 = np.array([[1,2,3], [4,5,6]])
print(arr5)
print(arr5.shape)

# 매트릭스 
# 2행 2열(2차원)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [29]:
arr6 = np.array([[[1,2,3], [4,5,6]]])
print(arr6)
print(arr6.shape)

# 텐서
# (1, 2, 3) = 2행 3열 매트릭스가 1개 있음(3차원) 

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)


In [33]:
arr7 = np.array([
        [
            [10, 20, 30, 40],
            [50, 60, 70, 80],
            [90, 100, 110, 120],
        ],
        [
            [100, 200, 300, 400],
            [500, 600, 700, 800],
            [900, 1000, 1100, 1200],
        ],
    ])
print(arr7)
print(arr7.shape)

# 3차원 텐서 

[[[  10   20   30   40]
  [  50   60   70   80]
  [  90  100  110  120]]

 [[ 100  200  300  400]
  [ 500  600  700  800]
  [ 900 1000 1100 1200]]]
(2, 3, 4)


In [34]:
# 차원수 알려주는 함수 
arr7.ndim

3

In [35]:
# 데이터의 개수 
print(arr7.size)
# arr7[1][0][2]  : 300 자리 찾기 

24


## np.arange()


In [5]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
print(list(range(5, 10)))
print(list(range(5, 10, 2)))

[5, 6, 7, 8, 9]
[5, 7, 9]


In [15]:
print(np.arange(1, 10))
print(np.arange(1, 10, 2))

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [17]:
arr1 = np.arange(10)

print(arr1[6])
print(type(arr1[6]))

6
<class 'numpy.int64'>


In [19]:
# u: Unsigned (부호를 없애는 타입)
arr2 = np.arange(10, dtype=np.uint8)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

## 넘파이의 자료형 
- int: 부호가 없는 정수 (8, 16, 32, 64)
- uimt: 부호가 없는 정수(8, 16, 32, 64)
- fioat: 실수(16, 32, 64, 128)
- complex: x 복소수(64, 128, 256)
- bool: 불리언(8)
- string_: x 문자열(8)
- object: 오브젝트 (64)

## astype (타입)
- 기존의 배열을 복사하고 타입을 변경하고 싶을떄 


In [21]:
arr2 = np.arange(10)
print(arr2.dtype)

int64


In [22]:
arr2 = arr2.astype(up.int8)
print(arr2.dtype)
print(arr3.dtype)

NameError: name 'up' is not defined

## npshape()
- ndarray의 형태와 차원을 바꾸기위해 사용하는 매서드 

In [5]:
arr3 = np.arange(12)

print(arr3.ndim)
print(arr3.shape)

1
(12,)


In [24]:
arr3.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
arr3.reshape(6, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [6]:
# 텐서 
arr3.reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [7]:
arr3.reshape(1, 2, 2, 3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]]])

In [8]:
arr3.reshape(1, 1, 4, 3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]]])

In [9]:
# reshape의 개수와, 데이터의 개수가 맞지 않으면 오류 
arr3.reshape(2, 2, 2, 2)

ValueError: cannot reshape array of size 12 into shape (2,2,2,2)

In [11]:
arr4 = np.arange(24).reshape(2,6,2)
arr4

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

## np.ones(), np.zeros()
- ndarray의 초기값을 0 또는 1로 설정학 위한 메서드 

In [13]:
arr5 = np.ones(8)
print(arr5)
print(type(arr5[0]))

[1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.float64'>


In [16]:
arr6 = np.zeros(8, dtype=np.int64)    # dtype : 타입 변경 
print(arr6)
print(type(arr6))
                

[0 0 0 0 0 0 0 0]
<class 'numpy.ndarray'>


In [17]:
arr6 = np.zeros(64, dtype=np.int64)
print(arr6)
print(type(arr6[0]))
                

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
<class 'numpy.int64'>


In [19]:
arr6.reshape(4, 16)



array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
arr6.reshape(2, 2, 16)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

## np.random
- rand: 0 ~ 1 사이의 균일 분포
- randn: 정규분포
- randint: 균일 분포 정규 난수

<img src="https://thebook.io/img/080263/218.jpg" />

In [21]:
np.random.randn(5)

array([ 0.7749208 , -1.49704467,  0.48073185,  1.18289156, -0.00611585])

In [22]:
# 0~4까지의 난수 
np.random.randint(5)

0

In [24]:
np.random.randint(50, 101)


69

In [25]:
np.random.randint?

Signature: np.random.randint(low, high=None, size=None, dtype=<class 'int'>)
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-lik

In [36]:
np.random.randint(1, 46, (2,3))

array([[30, 17,  7],
       [23,  3, 42]])

## seed()
- 난수를 예측가능하도록 만들며, 실행할 떄마다 동일한 난수를 발생시켜,  
  코드의 재형성 , 특정 알고리즘의 결과를 재현하게 만든다.또한 해당 알고리즈므의 결과의 오류를 추적허가 위해 사용한다 

In [38]:
# 랜덤한 번호 추적 
np.random.seed(4885)

np.random.randint(10, size=(2,5))

array([[9, 1, 0, 3, 4],
       [8, 7, 4, 7, 6]])

In [42]:
np.random.seed(4885)

# 0~1 (균등분포)
np.random.rand(10)

array([0.21350835, 0.56504926, 0.7597468 , 0.05666448, 0.6753598 ,
       0.36138766, 0.01299493, 0.04721084, 0.26603997, 0.8042786 ])

## unique()
- ndarray의 중복값을 제거해주는 함수 

In [43]:
np.unique([11, 11, 11, 11, 14, 15])


array([11, 14, 15])

## shape 변경 
## ravel(), np.ravel() 
- 다차원 배열을 1차원으로 변경하는 메서드 

In [47]:
arr7 = np.arange(24), reshape(2, 3, 4)
arr7

NameError: name 'reshape' is not defined

In [46]:
arr7.ravel()

NameError: name 'arr7' is not defined

In [48]:
# C: row방향 
arr7.ravel(order='C')

NameError: name 'arr7' is not defined

In [49]:
 # F: 
arr7.ravel(order='F')

NameError: name 'arr7' is not defined

In [ ]:
# axis0 = x축, axis1 = y축 

## np.flatten()
- copy를 생성하고 원본 배열을 변경하지 않는 복사본을 반환한다  

In [ ]:
arr7 = np.arange(24). rashape(2, 12)

print(arr7)
print(arr7.flatten())

In [52]:
# -1 : 차원 유추 
arr8 = np.arange(120).reshape(2, -1, 12)
arr8

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]])

## 차원 확장 
- np.expand_dims()
- axis로 지정 축을 확장시키는 메서드

In [53]:
arr8 = np.arange(10)
print(arr8.shape)

(10,)


In [56]:
# 행 하나더 추가 됨 
arr9 = np.expand_dims(arr8, axis=0)
print(arr9)
print(arr9.shape)

[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)


In [57]:
# 열이 하나 추가 되서 쪼개져서 들어감 
arr9 = np.expand_dims(arr8, axis=1)
print(arr9)
print(arr9.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


## 차원축소 
- squeeze(), np.squeeze()

In [58]:
print(arr9)
print(arr9.shape)
print(arr9.squeeze())

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)
[0 1 2 3 4 5 6 7 8 9]


## 전치 행렬(transpose), T
- 행과 열 변경 

In [59]:
# 2, 3 - > 3, 2
arr1 = np.arange(15).reshape(3, 5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
np.transpose(arr1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [63]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
arr2 = np.arange(12).reshape(

In [65]:
# T: transpose의 약자 
print(rr2.T)

NameError: name 'rr2' is not defined

In [64]:
print(arr2.fiatten())

NameError: name 'arr2' is not defined

## array간의 연산 


In [67]:
# 시퀀스 : 순서가 있는 자료구조 
# [1,2,3] + [1,2,3]

# 리스트 간의 연산 
arr1 = np.arange(15).reshape(3, 5)
arr1



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
# array + scalar 는 연산 가능 
# 2치원 + 0치원
# 2치원 
arr1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [73]:

arr1 + [10]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
## 2치원 + 2치원
# 2치원 
arr1 + [[10]]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
# 2치원 + 3치원
# 3치원 
arr1 + [[[10]]]

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

## 브로드캐스팅
- 다른 크기의 배열들 간에도 자동으로 연산해주는 Numpy의 강력한 기능

## 브로드캐스팅의 특징
    - 기본적으로는 shape와 같은 두 ndarray에 대한 연산은 각 원소별로 진행한다
    - 다른 shape를 갖는 array 간의 연산의 경우 브로드 캐스팅(shape를 맞춤) 후 진행한다

<img width=500 src='https://www.astroml.org/_images/fig_broadcast_visual_1.png' />

In [77]:
arr1 = np.arange(12).reshape(4, 3)
arr1

print(arr1.shape)
# (4행 3열)

(4, 3)


In [80]:
arr2 = np.arange(3)

print(arr2)
print(arr2.shape)
# 행 데이터 3개 

[0 1 2]
(3,)


In [81]:
print(arr1 + arr2)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


## 브로드 캐스팅의 규칙 
1. 뒷 차원부터 비교한더
2. shape가 같아야 한다 
3. 차원 중에 값이 1이 존재한다
4. [브로드캐스팅 공식문서](https://numpy.org/doc/stable/user/basics.broadcasting.html)

In [82]:
"""
    차원이 존재하는 경우 확장이 가능하다 
    6 x 1 x 5
        7 x 3

    6 x 7 x 5

"""

# 미리보기 안보려고 None 적음 
None

In [83]:
arr1 = np.arange(100, 104)
print(arr1)

[100 101 102 103]


In [86]:
# (4, 3)
# 
arr2 = np.arange(12).reshape(4, 3)
print(arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [87]:
arr1 + arr2


ValueError: operands could not be broadcast together with shapes (4,) (4,3) 

위 식이 연산이 안되는 이유 

<img src="https://numpy.org/doc/stable/_images/broadcasting_3.png" />

In [89]:
# (2, 3), (3, 2)
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(100, 106).reshape(3,2)

print(arr3)
print(arr4)

[[0 1 2]
 [3 4 5]]
[[100 101]
 [102 103]
 [104 105]]


In [90]:
# 차원수가 달라서 연산이 안됨 
arr3 + arr4

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [97]:
# 트렌스 포즈(= T)로 행 ,열 변환 
arr3.T + arr4

array([[100, 104],
       [103, 107],
       [106, 110]])

## 차원축(exsis)
- 1차원 arra라면 각 차원에 대한 axis 깂은 0
- 2차원 arra라면 각 차원에 대한 axis 깂은 0,1
- 3차원 arra라면 각 차원에 대한 axis 깂은 0,1,2,

In [98]:
arr1 = np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [102]:
# sum(arr1)
np.sum(arr1)

np.int64(105)

In [103]:
np.sum?

Signature:      
np.sum(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  np.sum(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sum at 0x107a35440>
File:            /opt/anaconda3/envs/analysis/lib/python3.12/site-packages/numpy/_core/fromnumeric.py
Docstring:      
Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis. If
    axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements

In [104]:
np.sum(arr1, axis= 0)

np.int64(105)

In [106]:
arr1 = np.arange(15).reshape(3, 5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [112]:
print(np.sum(arr1, axis=0))   # y축 다 더한 값
print(np.sum(arr1, axis=1))  # x축 다 더한값

[15 18 21 24 27]
[10 35 60]


In [117]:
arr2 = np.arange(24).reshape(2,3,4)
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [115]:
np.sum(arr2, axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [118]:
np.sum(arr2, axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [119]:
np.sum(arr2, axis=-1)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [120]:
arr2.shape

(2, 3, 4)

## ⭐️ argmax()
- 최대값의 인덱스

In [121]:
arr3 = np.arange(5, 10)
print(arr3)

# [5 6 7 8 9]에서 제일 큰 값은 9
print(arr3[arr3.argmax()])

[5 6 7 8 9]
9


In [128]:
np.random.seed(918)
# np.raarr4.argmaxndom.randint(10, size=(0,6))
arr4 = np.random.randint(10, size=(1,6)).flatten()
print(arr4.argmax()) # 가장 큰 값의 인덱스
print(arr4.argmin())  # 가장 작은 값의 인덱스 
print(arr4.max())   # 가장 큰 값
print(arr4.min())   # 가장 작은 값
print(argmax(arr4))

0
4
9
2


NameError: name 'argmax' is not defined

In [129]:
arr5 = np.random.randint(10, size=(3,6))
arr5

array([[0, 6, 5, 0, 8, 5],
       [3, 4, 6, 8, 1, 8],
       [4, 8, 2, 3, 7, 7]])

In [130]:
# 출력 방향 x축 ,연산은 y축방향에 있는 숫자 연산
print(arr5.argmax(axis=0))

# 출력 방향 y축 ,연산은 x축방향에 있는 숫자 연산
print(arr5.argmax(axis=1))

[2 2 1 1 0 1]
[4 3 1]


In [132]:
# x축 방향 큰 값 / 작은 값 

print(arr5.max(axis=0))
print(arr5.min(axis=0))

[4 8 6 8 8 8]
[0 4 2 0 1 5]


## boolean selection, boolean indexing
- array 인덱싱 시 , bool 타입의 조건에 맞는 list를 전달하여 조건식을 만족하는 True 의 결과불만 필ㅌ링 한다 

In [134]:
arr4 = np.random.randint(1, 100, size=20)
print(arr4)

[39 22 55 93 43 16 97 45 71 33 71 46 44 67 23 84 26 42 31 96]


In [138]:
print(arr4 / 5)
print(arr4 % 2)  # 결가 가 0이 나오면 짝수 이고 1이 나오면 홀수

even_mask = arr4 % 2 == 0
print(even_mask)

[ 7.8  4.4 11.  18.6  8.6  3.2 19.4  9.  14.2  6.6 14.2  9.2  8.8 13.4
  4.6 16.8  5.2  8.4  6.2 19.2]
[1 0 1 1 1 0 1 1 1 1 1 0 0 1 1 0 0 0 1 0]
[False  True False False False  True False False False False False  True
  True False False  True  True  True False  True]


## 다중 조건식 
- &: and 조건식
- |: or 조건식 


In [5]:
# 홀수 이면서 50보다 작은 값
# and:
np.random.seed(2026)
arr5 = np.random.randint(100, size=15) 
arr5

array([ 1,  6, 26, 56, 77, 77, 29, 28, 51, 69, 76, 28,  2, 54, 77])

In [8]:
is_bound = (arr5 % 2 == 1) & (arr5 < 50)
arr5[is_bound]

array([ 1, 29])

In [7]:
arr5[is_bound].astype(str)

array(['1', '29'], dtype='<U21')