## 파이토치(PyTorch) 프레임워크란?
- 파이토치(PyTorch)는 메타에서 개발한 파이썬 기반 오픈소스 딥러닝 프레임워크로, GPU 병렬 연산과 자동 미분 기능을 제공합니다.  
실행 시점에 그래프가 결정되는 동적 계산 방식을 채택해 복잡한 조건문과 반복문 구조도 제약 없이 유연하게 처리할 수 있습니다.  
파이썬 고유의 직관적인 코드 작성 방식을 지원하므로 디버깅과 수정이 용이하며 전체적인 모델 연구 및 개발 속도를 획기적으로 줄여줍니다.

- 즉, 머신러닝 딥러닝을 만들 수 있는 개발 환경입니다. 현업 파이토치8: 텐서플로우2


[파이토치 공식문서](https://docs.pytorch.org/docs/2.14/index.html)

## 1.스칼라(scalar)
- 스칼라는 정수나 실수처럼 단 하나의 숫자만을 표현하는 가장 기본적인 자료형이다 
    파이토치에서는 이 스칼라를 차원이 존재하지 않은 0차원 텐서 형태로 다릅니다

In [1]:
import torch
import numpy as np


In [2]:
num1= torch.tensor(10)
num2= torch.tensor(1.5)

print(num1)
print(num2)
print(type(num1))
print(type(num2))
# 스칼라

tensor(10)
tensor(1.5000)
<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [19]:
# 문자열 XX 숫자형만  
s = torch.tensor("단비")
print(s)

TypeError: new(): invalid data type 'str'

#### 모델은 컴퓨터를 학습시키는것을 의미하며, 학습은 모두 숫자형으로만 가능하다. 즉 tensor는 숫장자료형 밖에 넣을 수 없다 

In [4]:
# (torch가 가지고 있는)dtype : 데이터 타입
# 1차원 
num3 = torch.tensor([10], dtype=torch.float64)
print(num3)

tensor([10.], dtype=torch.float64)


In [5]:
num4 = torch.tensor([20], dtype=torch.int64)
print(num4)

tensor([20])


In [6]:
num3 = torch.tensor([20], dtype=torch.long)  # .long: 큰 자료형 
print(num3)

tensor([20])


In [7]:
# 2차원 텐서 
num6 = torch.tensor([[60]])
print(num6)

tensor([[60]])


### .item()
- 텐서 자료형에서 값을 꺼내오는 메서드 

In [8]:
# 텐서 자료형에서 가져옴 
print(num3.item())

20


## 텐서간의 연산 

In [9]:
print(num1)
print(num2)
# <class 'torch.Tensor'>  : 모두 텐서로 바로 바꿔줌 

print(num1 + num2)

tensor(10)
tensor(1.5000)
tensor(11.5000)


In [10]:
print(num1)   # 1차원
print(num3)   # 0차원


print(num1+ num3)

tensor(10)
tensor([20])
tensor([30])


In [11]:
# 0차원 + 2차원  -> 2차원 
print(num1, num6)
print(num1 +  num6)

tensor(10) tensor([[60]])
tensor([[70]])


## 0차원 값과 다차원 값을 연산하면 다차원의 값으로 반환한다 ex) 0차원 + 2차원  = 2차원


## 2) 백터(Vector)
1) 하나 이상의 원소가 일렬로 나열된 1차원 텐서 형태의 자료구조를 의미함
2) 파이토치에서는 n의 원소가 담긴 백터는 (n, )형태의 차원을 갖게됩니다 

In [12]:
v1 = torch.tensor([1.0, 2.0, 3.0])      # 
v2 = torch.tensor([10.0, 20.0, 30.0])

In [13]:
print(v1)
print(v2)

# 텐서의 차원별 크기 구하기  - torch.Size([3]) : 1차원에 원소 3개 
print(v2.shape)
print(v2.size())

tensor([1., 2., 3.])
tensor([10., 20., 30.])
torch.Size([3])
torch.Size([3])


In [14]:
print(num1)
print(v1 + num1)

tensor(10)
tensor([11., 12., 13.])


In [15]:
# 브로드 캐스팅 가능  : 모양이 다른 텐서끼리도 자동으로 크기에 맞춰 연산하는 기능 
# 주의 사항 : 열의 갯수가 같아야함 
print(v1 + v2)

tensor([11., 22., 33.])


## 행렬 (Matrix)
- 행과 열로 이루어진 2차원의 형태의 텐서를  . 예를 들어 2행 2얄의 데이터라면 torch.tensor([1, 2], [3, 4])로 표시되며
  행렬곱 연산이 가능 합니다 파이토치에서 행렬 연산은 

In [16]:
mt1 = torch.tensor([[1, 2], [3, 4]])
mt2 = torch.tensor([[10, 20], [30, 40]])

print(mt1)    # 매트릭스 
print(type(mt1))   #2차원 텐서 
print(mt1.shape)    # torch.Size([2, 2]): 2행 2열   

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
torch.Size([2, 2])


In [17]:
# 브로드 캐스팅 (크기가 다른 텐서끼리도, 규칙에 맞으면 자동으로 크기를 맞춰 연산하는 기능)
# mt1: [1, 2],[3, 4] , num1 (: 10)  -> (브로드 캐스팅해서)[10, 10][10, 10] (으로 바뀜)
print(mt1 + num1)
print(mt1 + mt2)

tensor([[11, 12],
        [13, 14]])
tensor([[11, 22],
        [33, 44]])


In [18]:
# 열의 개수가 달르면 안됨 ->()
print(mt  + v1)

NameError: name 'mt' is not defined

In [20]:
# 치원은 달라도 됌 
# 차원은 달라도 상관이 없으나, 열의 개수가 다르면 연산할 수 없다.(차원은 크기 맞춤)
print(mt1 + torch.tensor([100, 200]))

tensor([[101, 202],
        [103, 204]])


## 4) 텐서 

In [21]:
data = [
    [1, 2], 
    [3, 4]
]
t1 = torch.tensor(data)
print(t1)

tensor([[1, 2],
        [3, 4]])


In [22]:
[1, 2] + [3, 4]
# 시퀀스 자료구조 끼리 연산 -> 시퀀스 연산자
# 브로드 캐스팅을 하려면 넘파이 아님 탠거만 가능 

[1, 2, 3, 4]

### tensor -> ndarray

In [24]:
print(t1)
print(type(t1), end="\n\n")
print(t1.numpy())
print(type(t1.numpy()))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


## tensor -> ndarray

In [25]:
ndarray1 = np.array([10, 20, 30])   # NumPy 배열
print(ndarray1)

# NumPy 배열(ndarray1)을 PyTorch 텐서로 바꾸고 출력
print(torch.from_numpy(ndarray1))

[10 20 30]
tensor([10, 20, 30])


In [26]:
t3 = torch.tensor([
    [1, 2, 3, 4],
    [10, 20, 30, 40],
    [5, 6, 7, 8]
])
print(t3)
print(t3.size())

# 인덱싱 가능 
print(t3[1])

tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40],
        [ 5,  6,  7,  8]])
torch.Size([3, 4])
tensor([10, 20, 30, 40])


In [27]:
# 슬라이싱  가능 
print(t1[1:2])

tensor([[3, 4]])


In [28]:
print(t3)


tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40],
        [ 5,  6,  7,  8]])


In [29]:
# 모든 행의 마지막 열의 0번 
print(t3[:, 0])  
                    # 위아래 같은 값 
print(t3[..., 0])

tensor([ 1, 10,  5])
tensor([ 1, 10,  5])


In [31]:
np.arange(1, 13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
# 차원 바꿈 ->  2행 3열 2개  
t4 = np.arange(1, 13).reshape(2, 2, 3)
t4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# -1 : 알아서 바꿔라 
t4 = np.arange(1, 13).reshape(2, -1, 3)
t4

In [ ]:
t5 = torch.from_numpy(t4)
t5

In [ ]:
print(t5[:, 0])

In [ ]:
print(t5[..., 0])

## 5. 행렬곱 

## 내적(Dot Product) 계산 및 개념

### 개념
- 내적은 두 벡터 간의 원소별 곱을 모두 더하는 연산으로, 두 벡터가 얼마나 같은 방향을 향하는지 나타내는 유사도(방향성 일치도)의 척도입니다.

### 내적 공식
3차원 벡터 A = (x1, y1, z1)와 B = (x2, y2, z2)의 내적 공식은 다음과 같습니다.

A · B = x1*x2 + y1*y2 + z1*z3

- 첫 번째 성분끼리 곱하기: 1 x 11 = 11
- 두 번째 성분끼리 곱하기: 2 x 12 = 24
- 세 번째 성분끼리 곱하기: 3 x 13 = 39
- 최종 내적 값: 11 + 24 + 39 = 74 (0차원 스칼라)

### 내적과 행렬곱의 관계
1차원, 2차원, 3차원 텐서 모두 행렬곱 연산이 가능하며, 행렬곱의 결과 형태(Shape)는 입력되는 행렬들의 크기에 따라 다르게 결정됩니다. 행렬곱을 이루는 각 위치의 원소를 계산하는 본질적인 연산 방식이 바로 벡터의 내적이며, (1, n) 행렬과 (n, 1) 행렬의 곱처럼 결과가 1x1 형태의 2차원 행렬로 나오는 경우 그 내부 원소 값은 두 벡터의 내적 값(0차원 스칼라)과 동일합니다.

In [ ]:
정리!
행열곱은 행과 다른 행렬의 열을 곱해서 더하는 계산임
A = [1  2]      B = [5]
    [3  4]          [6]
A는 2행 2열 , B는 2행 1열인데  

In [32]:
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([1, 2, 3])

print(v1)
print(v2)

tensor([1, 2, 3])
tensor([1, 2, 3])


In [33]:
print(torch.matmul(v1, v2))

tensor(14)


In [ ]:
"""
    1차원 벡터 내적 [1, 2, 3] x [1, 2, 3]
    (3,) 크기를 가지는 1차원 벡터 2개의 내적 연산 과정입니다.

    - 첫 번째 성분끼리 곱하기: 1 x 1 = 1
    - 두 번째 성분끼리 곱하기: 2 x 2 = 4
    - 세 번째 성분끼리 곱하기: 3 x 3 = 9
    - 최종 연산 결과: 1 + 4 + 9 = 14
"""

None

In [34]:
# 가로 백터 (1행 3열), 세로 백터 (3행 1열) 을  행렬곱해서 값 하나를 가진 1행 1열 행렬을 만듬 
# []의 갯수 = 행  \  안에 들어가 있는 숫자의 갯수 = 열

v3 = torch.tensor([[1, 2, 3]])
v4 = torch.tensor([[1], [2], [3]])

print(v3)
print(v4)


print(v3.shape)
print(v4.shape)

# [1 2 3] X [1]  = 1x1 + 2x2 + 3X3
# 1 + 4 + 9
# 14

print(torch.mm(v3, v4))

tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])
torch.Size([1, 3])
torch.Size([3, 1])
tensor([[14]])


In [36]:
# 크기가 같아서 덧셈, 행렬곱 둘다 가능
m3 = torch.tensor([[1, 2],[3, 4]])
m4 = torch.tensor([[5, 6],[7, 8]])

# [1 2][5 6] = [1X5 + 2X7 , 1X6 + 2X8]
# [3 4][7 8] = [3X5 + 4X6 , 3X6 + 4X8]

print(m3)
print(m4)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])


In [38]:
# - 19 = [1, 2]와 [5, 7]
# - 22 = [1, 2]와 [6, 8]
# - 43 = [3, 4]와 [5, 7]
# - 50 = [3, 4]와 [6, 8]
print(torch.mm(m3, m4))

tensor([[19, 22],
        [43, 50]])


In [41]:
"""
    2x2 행렬곱 [[1, 2], [3, 4]] x [[5, 6],
                                 [7, 8]]

    - 첫 번째 행 × 첫 번째 열:
      1 x 5 + 2 x 7 = 19

    - 첫 번째 행 × 두 번째 열:
      1 x 6 + 2 x 8 = 22

    - 두 번째 행 × 첫 번째 열:
      3 x 5 + 4 x 7 = 43

    - 두 번째 행 × 두 번째 열:
      3 x 6 + 4 x 8 = 50

    - 최종 연산 결과:
      [[19, 22], [43, 50]]

      내적이 클수록 → 같은 방향에 가까움
      내적이 작을수록 → 같은 반대에 가까움
"""

None

In [40]:
a = torch.tensor([1, 2], dtype=torch.float32)
b = torch.tensor([3, 4], dtype=torch.float32)

diff = a - b
# [1, 2] - [3, 4]
# = [1-3, 2-4]
# = [-2, -2]
print(diff)

# torch.norm()은 벡터의 길이를 구함 
        # distance = √((-2)² + (-2)²)
        #          = √(4 + 4)
        #          = √8
        #          ≈ 2.8284
distance = torch.norm(diff)
print(distance)

tensor([-2., -2.])
tensor(2.8284)


## 파이토치의 핵심 장점: GPU 활용과 연산 가속
- GPU(Graphics Processing Unit)는 본래 이미지 렌더링과 같은 대규모 병렬 계산을 처리하기 위해 설계된 그래픽 처리 장치입니다.  
  하지만 최근에는 수많은 행렬 및 벡터 연산이 필요한 인공지능(AI)과 딥러닝 분야에서 뛰어난 연산 가속기로 널리 활용되고 있습니다.  
  GPU는 다수의 코어를 통해 수천, 수만 개의 연산을 동시에 병렬로 처리할 수 있는 구조를 갖추고 있어 딥러닝 모델 학습에 매우 최적화되어 있습니다.
- 파이토치에서 이러한 GPU 가속을 활용하기 위해서는 외장 그래픽카드와 함께 전용 하드웨어 설치 프로그램(예: NVIDIA CUDA 등)을 갖추어야 하며,  
  내장 그래픽 환경에서는 사용이 불가능합니다. 만약 로컬에 적합한 그래픽 카드가 없는 경우, 구글 코랩(Google Colab) 환경을 이용하면  
  무료로 GPU 가속을 사용해 볼 수 있습니다.
- 한편, 머신러닝과 딥러닝 전용으로 개발된 또 다른 가속 장치인 TPU(Tensor Processing Unit)의 경우,  
  본래 텐서플로(TensorFlow) 환경에 최적화되어 있어 파이토치에서는 직접적인 사용 및 적용이 다소 제한적입니다.  
  따라서 파이토치를 활용한 딥러닝 연산 시에는 GPU 환경을 구축하고 사용하는 것이 가장 일반적이고 효율적인 방법입니다.

In [42]:
print("Cuda 사용 가능 여부:", torch.cuda.is_available())
print("Mps 사용 가능 여부:", torch.mps.is_available())
print("Cpu 사용 가능 여부:", torch.cpu.is_available())
print("Xpu(Itel 내장 그래픽)사용가능 여부 :", torch.xpu.is_available())

Cuda 사용 가능 여부: False
Mps 사용 가능 여부: True
Cpu 사용 가능 여부: True
Xpu(Itel 내장 그래픽)사용가능 여부 : False


In [43]:
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.mps.is_available():
    device = torch.device("mps")
elif torch.xpu.is_available():
    device = torch.device("xpu")
else:
    device = torch.device("cpu")

print(f"현재 선택된 장치: {device}")

현재 선택된 장치: mps


In [44]:
t1 = torch.tensor([10])

# .to(device) : 텐서를 지정한 장치로 옮김 
t1_gpu = t1.to(device)

print(t1)      # -> CPU 메모리 
print(t1_gpu)  # -> GPU 메모리 

# cpu와 gpu의 영역이 다르기 때문에 연산이 안됨 
print(t1 + t1_gpu)

tensor([10])
tensor([10], device='mps:0')


RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!

In [48]:
print(t1.is_cpu)
print(t1_gpu.is_cuda)
print(t1_gpu.is_mps)
print(t1_gpu.is_xpu)

True
False
True
False


# GPU 연산 

In [56]:
t2 = torch.tensor([[1, 2], [3, 4]])
t3 = torch.tensor([[10, 20], [30, 40]])

# .to(device): 텐서를 device가 가리키는 곳으로 옮깁니다
# device : 텐서가 저장되고 계산될 장서를 담아둔 변수 -> mps
t2_gpu = t2.to(device)
t3_gpu = t3.to(device)

In [57]:
print(t2_gpu)
print(t3_gpu)

tensor([[1, 2],
        [3, 4]], device='mps:0')
tensor([[10, 20],
        [30, 40]], device='mps:0')


In [61]:
# [1+10   2+20] = [11  22]
# [3+30   4+40]   [33  44]
print(t2_gpu + t3_gpu)
# [1×10   2×20] = [10   40]
# [3×30   4×40]   [90  160]
print(t2_gpu * t3_gpu)
# [1÷10   2÷20] = [0.1  0.1]
# [3÷30   4÷40]   [0.1  0.1]
print(t2_gpu / t3_gpu)
# [1-10   2-20] = [-9   -18]
# [3-30   4-40]   [-27  -36]
print(t2_gpu - t3_gpu)

tensor([[11, 22],
        [33, 44]], device='mps:0')
tensor([[ 10,  40],
        [ 90, 160]], device='mps:0')
tensor([[0.1000, 0.1000],
        [0.1000, 0.1000]], device='mps:0')
tensor([[ -9, -18],
        [-27, -36]], device='mps:0')


In [63]:
print(t2_gpu)
# 1 + 2 + 3 + 4 = 10 
print(t2_gpu.sum())
# [1+3, 2+4] [4, 6]  : (dim=0)세로 방향으로 더함 
print(t2_gpu.sum(dim=0))
# [1+2, 3+4]  : (dim=1)가로 방향으로 더함 
print(t2_gpu.sum(dim=1))

tensor([[1, 2],
        [3, 4]], device='mps:0')
tensor(10, device='mps:0')
tensor([4, 6], device='mps:0')
tensor([3, 7], device='mps:0')


In [64]:
t4 = t3_gpu.to(torch.float32)
print(t4)
print(t4.mean())
print(t4.mean(dim=0))
print(t4.mean(dim=1))

tensor([[10., 20.],
        [30., 40.]], device='mps:0')
tensor(25., device='mps:0')
tensor([20., 30.], device='mps:0')
tensor([15., 35.], device='mps:0')


In [58]:
print(m4.min())
print(m4.max())

tensor(5)
tensor(8)


In [65]:
print(t4)
# 가장 큰 값/작은 값 이 있는 위치 정보 (인덱스 번호)
print(t4.argmax(dim=1))
print(t4.argmin())

tensor([[10., 20.],
        [30., 40.]], device='mps:0')
tensor([1, 1], device='mps:0')
tensor(0, device='mps:0')


In [66]:
print(torch.flatten(t4))
torch.flatten(t4).argmax()

tensor([10., 20., 30., 40.], device='mps:0')


tensor(3, device='mps:0')

## 6) 텐서의 차원 조작


In [68]:
torch.tensor(np.arange(1, 13).reshape(3, 4))
t1 = torch.from_numpy(np.arange(1, 13).reshape(3, 4))
t1

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

#### .cat(): 기존의 텐서를 연결하는 메서드 

In [69]:
# [1, 2, 3] 는 파이썬 리스트이기 때문에 오류남 \ torch.cat()에는 텐서만 넣을 수 있음 
torch.cat([t1, [1, 2, 3]], dim=0)

TypeError: expected Tensor as element 1 in argument 0, but got list

In [70]:
# t1은 (3, 4): 3행 4열 
        # 첫 번째 t1
        # [ 1   2   3   4]
        # [ 5   6   7   8]
        # [ 9  10  11  12]
        
        # 두 번째 t1
        # [ 1   2   3   4]
        # [ 5   6   7   8]
        # [ 9  10  11  12]
torch.cat([t1, t1], dim=0)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [71]:
# dim=1 : 오른쪽으로 붙이기 
        # [ 1   2   3   4 |  1   2   3   4]
        # [ 5   6   7   8 |  5   6   7   8]
        # [ 9  10  11  12 |  9  10  11  12]
torch.cat([t1, t1], dim=1)

tensor([[ 1,  2,  3,  4,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  5,  6,  7,  8],
        [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [72]:
v1 = torch.tensor(range(1, 5))
v1

tensor([1, 2, 3, 4])

In [73]:
v1[2] = 300
v1

tensor([  1,   2, 300,   4])

In [74]:
v2 = torch.tensor(range(1, 5))
# .clone() : 원본 배열과 값을 공유하지 않은 복사본을 생성 
v3 = v2.clone()
v2

tensor([1, 2, 3, 4])

In [75]:
v3[0] = 1000

print(v2)
print(v3)

tensor([1, 2, 3, 4])
tensor([1000,    2,    3,    4])


In [79]:
# reshape : 텐서 안에 있는 순서는 그대로 두고 행과 열 모양만 바꾸는 함수  
v2.reshape(2, 2)

tensor([[1, 2],
        [3, 4]])

In [81]:
# view : 텐서의 모양만 바꾸는 함수 
v2.view(2, 2)

tensor([[1, 2],
        [3, 4]])

In [84]:
# rand : 0 이상 1미만의 무작위 실수를 만드는 함수 
# (10, 3, 4) 인 3차원 텐서르 만듬 
#  10개 묶음  -각 묶음은 3행  -각 행은 4개 숫자  (각 묶음은 3X4)
t1 = torch.rand((10, 3, 4))
print(t1)


tensor([[[0.6444, 0.8248, 0.7269, 0.1307],
         [0.7170, 0.5346, 0.0690, 0.7115],
         [0.2107, 0.7672, 0.3484, 0.5041]],

        [[0.8014, 0.1747, 0.7661, 0.5213],
         [0.7164, 0.3705, 0.0383, 0.6991],
         [0.9512, 0.4809, 0.5876, 0.4523]],

        [[0.5902, 0.3462, 0.5383, 0.8395],
         [0.8729, 0.1650, 0.2831, 0.5947],
         [0.8696, 0.3561, 0.6574, 0.6949]],

        [[0.6512, 0.9231, 0.4924, 0.3934],
         [0.4204, 0.5548, 0.3606, 0.8973],
         [0.2744, 0.9050, 0.4470, 0.3247]],

        [[0.7972, 0.7845, 0.2199, 0.1250],
         [0.3045, 0.2644, 0.1841, 0.2255],
         [0.1664, 0.4500, 0.0880, 0.1354]],

        [[0.3773, 0.4524, 0.0735, 0.4075],
         [0.7756, 0.2393, 0.7284, 0.0543],
         [0.6509, 0.1615, 0.7364, 0.2620]],

        [[0.3893, 0.1137, 0.4196, 0.8924],
         [0.5546, 0.1590, 0.1767, 0.8316],
         [0.4685, 0.6666, 0.4761, 0.0995]],

        [[0.8925, 0.1188, 0.5022, 0.4815],
         [0.1432, 0.2547, 0.4039, 0.2346

In [88]:
print(t1.shape)

torch.Size([10, 3, 4])


### .permute()
- 차원 변경

In [92]:
print(t1.shape)
t2 = t1.permute(2, 1, 0)  # 인넥스 위치 
print(t2.shape)

torch.Size([10, 3, 4])
torch.Size([4, 3, 10])


In [94]:
# torch.randint() : 무작위 정수를 만드는 함수 
# low=0 : 최소값은 0
# high=10 : 10개 묶음 x 3행 x 4열 
t3 = torch.randint(low=0, high=10, size=(10, 3, 4))
t3

tensor([[[8, 5, 9, 0],
         [2, 7, 3, 3],
         [6, 3, 1, 1]],

        [[3, 8, 0, 7],
         [3, 4, 3, 6],
         [1, 6, 0, 4]],

        [[1, 9, 1, 6],
         [0, 0, 8, 6],
         [0, 4, 7, 3]],

        [[3, 0, 3, 8],
         [6, 7, 5, 4],
         [1, 2, 4, 3]],

        [[2, 0, 2, 4],
         [7, 5, 1, 1],
         [8, 4, 6, 6]],

        [[9, 3, 7, 8],
         [6, 4, 1, 9],
         [4, 1, 2, 0]],

        [[9, 4, 8, 0],
         [3, 3, 0, 9],
         [4, 6, 0, 9]],

        [[5, 5, 3, 8],
         [1, 9, 6, 2],
         [1, 7, 3, 5]],

        [[4, 2, 9, 3],
         [1, 7, 5, 1],
         [5, 9, 6, 6]],

        [[7, 8, 8, 5],
         [7, 8, 9, 0],
         [7, 2, 1, 8]]])

In [101]:
# 0번에 위치애 1차원짜리 하나 추가 (묶음 1개 추가)
t4 = t3.unsqueeze(0)
print(t3.shape)
print(t4.shape)

torch.Size([10, 3, 4])
torch.Size([1, 10, 3, 4])


In [102]:
# squeeze() : 크기 1인 차원 제거 
t5 = t4.squeeze()
print(t5.shape)


torch.Size([10, 3, 4])


## 자동 미분과 기울기(requires_grad)
### 미분
- 어떤 값(변수)이 아주 조금 바뀔 때, 그에 따라 다른 값이 얼마나 변하는 지 계산하는 방법이다.

$$
\frac{\Delta y}{\Delta x}
$$

이는 x가 변한 만큼 y가 얼마나 변했는지를 나타냅니다.

예를 들어:

$$
x: 2 \rightarrow 3
$$

이면

$$
\Delta x = 1
$$

그리고

$$
y: 4 \rightarrow 7
$$

이면

$$
\Delta y = 3
$$

따라서

$$
\frac{\Delta y}{\Delta x}
=
\frac{3}{1}
=
3
$$

이것을 평균 변화율이라고 합니다.

미분은 변화량을 0에 가깝게 줄였을 때의 변화율을 의미합니다.

$$
\frac{dy}{dx}…

## 순전파 (Forward Pass): out 계산
### 1) 입력 벡터 정의
$$x = [x_1, x_2] = [3.0, 4.0]$$
$$y = [y_1, y_2] = [1.0, 2.0]$$

### 2) z = x + y 연산
각 성분별로 더해져 새로운 2차원 벡터 $z$가 생성됩니다.
$$z_1 = x_1 + y_1 = 3.0 + 1.0 = 4.0$$
$$z_2 = x_2 + y_2 = 4.0 + 2.0 = 6.0$$
$$z = [4.0, 6.0]$$

### 3) out = z.mean() 연산
벡터 $z$의 모든 성분을 더한 뒤 성분의 개수($n=2$)로 나누어 평균을 구합니다.
$$out = \frac{z_1 + z_2}{2} = \frac{4.0 + 6.0}{2} = 5.0$$

In [ ]:
# 순전파⭐️
# 각 가중치를 구해서 다 곱해서 out을 구하는 과정 
# 값과 가중치를 곱하고 곱한것끼리 더해서 y값을 구하는 것

## 2. 역전파 (Backward Pass): 미분 계산

`out.backward()`가 호출되면 연쇄 법칙(Chain Rule)에 의해 최종 출력($out$)에 대한 각 입력 성분들의 미분 값(기울기)이 역순으로 계산됩니다.

### 1) out에 대한 z의 편미분
$$out = \frac{1}{2}z_1 + \frac{1}{2}z_2$$
$$\frac{\partial out}{\partial z_1} = 0.5, \quad \frac{\partial out}{\partial z_2} = 0.5$$

### 2) 연쇄 법칙을 통한 최종 미분 계산 (x와 y 기준)
$z_1 = x_1 + y_1$ 이므로 $\frac{\partial z_1}{\partial x_1} = 1$ 입니다. 이를 활용해 최종 미분 값을 구합니다.

* **x에 대한 미분 값:**
  $$\frac{\partial out}{\partial x_1} = \frac{\partial out}{\partial z_1} \times \frac{\partial z_1}{\partial x_1} = 0.5 \times 1 = 0.5$$
  $$\frac{\partial out}{\partial x_2} = \frac{\partial out}{\partial z_2} \times \frac{\partial z_2}{\partial x_2} = 0.5 \times 1 = 0.5$$

* **y에 대한 미분 값 (위와 동일):**
  $$\frac{\partial out}{\partial y_1} = 0.5, \quad \frac{\partial out}{\partial y_2} = 0.5$$

In [105]:
# x, y는 실수형 백터 ,
# equires_grad=True : 이 텐서가 결과에 얼마나 영향을 주는지 미분값을 계산(딥러닝 학습)
x = torch.tensor([3.0, 4.0], requires_grad=True) 
y = torch.tensor([1.0, 2.0], requires_grad=True) 

print(x, y)

# 순전파  
# (x + y) : 같은 위치끼리 더함 -> .mean : 평균 구함
# x + y = [3+1, 4+2] = [4, 6] -> (4+6) ÷ 2 = 5
# out = ((x1 + y1) + (x2 + y2)) ÷ 2
# out = (x1 + y1 + x2 + y2) ÷ 2

out = (x + y).mean()
print(out)

tensor([3., 4.], requires_grad=True) tensor([1., 2.], requires_grad=True)
tensor(5., grad_fn=<MeanBackward0>)


In [103]:
# ⭐️ 역전파 
# out이 x, y에 대해 얼마나 변하는지 거꾸로 미분해서 계산

out.backward()

In [104]:
# .grad는 “이 값이 결과에 얼마나 영향을 주는가”를 저장
print(f"x.grad: {x.grad}")
print(f"y.grad: {y.grad}")

# x의 첫 번째 값이 1 커지면 out은 0.5 커짐
# x의 두 번째 값이 1 커져도 out은 0.5 커짐
# y의 값들도 마찬가지

x.grad: tensor([0.5000, 0.5000])
y.grad: tensor([0.5000, 0.5000])
