## 파이토치(PyTorch) 프레임워크란?
- 파이토치(PyTorch)는 메타에서 개발한 파이썬 기반 오픈소스 딥러닝 프레임워크로, GPU 병렬 연산과 자동 미분 기능을 제공합니다.  
실행 시점에 그래프가 결정되는 동적 계산 방식을 채택해 복잡한 조건문과 반복문 구조도 제약 없이 유연하게 처리할 수 있습니다.  
파이썬 고유의 직관적인 코드 작성 방식을 지원하므로 디버깅과 수정이 용이하며 전체적인 모델 연구 및 개발 속도를 획기적으로 줄여줍니다.

- 즉, 머신러닝 딥러닝을 만들 수 있는 개발 환경입니다. 현업 파이토치8: 텐서플로우2


[파이토치 공식문서](https://docs.pytorch.org/docs/2.14/index.html)

## 1.스칼라(scalar)
- 스칼라는 정수나 실수처럼 단 하나의 숫자만을 표현하는 가장 기본적인 자료형이다 
    파이토치에서는 이 스칼라를 차원이 존재하지 않은 0차원 텐서 형태로 다릅니다

In [2]:
import torch
import numpy as np


In [6]:
num1= torch.tensor(10)
num2= torch.tensor(1.5)

print(num1)
print(num2)
print(type(num1))
print(type(num2))
# 스칼라

tensor(10)
tensor(1.5000)
<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [7]:
s = torch.tensor("단비")
print(s)

TypeError: new(): invalid data type 'str'

### 모델은 컴퓨터를 학습시키는것을 의미하며, 학습은 모두 숫자형으로만 가능하다. 즉 tensor는 숫장자료형 밖에 넣을 수 없다 

In [9]:
num3 = torch.tensor([10], dtype=torch.float64)
print(num3)

tensor([10.], dtype=torch.float64)


In [10]:
num4 = torch.tensor([20], dtype=torch.float64)
print(num4)

tensor([20.], dtype=torch.float64)


In [11]:
num3 = torch.tensor([20], dtype=torch.long)  # 큰 타입
print(num3)

tensor([20])


In [13]:
# 2차원 텐서 
num6 = torch.tensor([[60]])
print(num6)

tensor([[60]])


### .item()
- 텐서 자료형에서 값을 꺼내오는 메서드 

In [15]:
# 
print(num3.item())

20


## 텐서간의 연산 

In [16]:
print(num1)
print(num2)

print(num1 + num2)

tensor(10)
tensor(1.5000)
tensor(11.5000)


In [18]:
print(num1)   # 1차원
print(num3)   # 0차원


print(num1+ num3)

tensor(10)
tensor([20])
tensor([30])


In [19]:
print(num1, num6)
print(num1 +  num6)

tensor(10) tensor([[60]])
tensor([[70]])


## 0차원 값과 다차원 값을 연산하면 다차원의 값으로 반환한다 ex) 0차원 + 2차원  = 2차원


## 2) 백터(Vector)
1) 하나 이상의 원소가 일렬로 나열된 1차원 텐서 형태의 자료구조를 의미함
2) 파이토치에서는 n의 원소가 담긴 백터는 (n, )형태의 차원을 갖게됩니다 

In [22]:
v1 = torch.tensor([1.0, 2.0, 3,0])
v2 = torch.tensor([10.0, 20.0, 30])

In [23]:
print(v1)
print(v2)

print(v2.shape)
print(v2.shape())


tensor([1., 2., 3., 0.])
tensor([10., 20., 30.])
torch.Size([3])


TypeError: 'torch.Size' object is not callable

In [ ]:
print(num1)
print(num1)

## 행렬 (Matrix)
- 행과 열로 이루어진 2차원의 형태의 텐서를  . 예를 들어 2행 2얄의 데이터라면 torch.tensor([1, 2], [3, 4])로 표시되며
  행렬곱 연산이 가능 합니다 파이토치에서 행렬 연산은 

In [24]:
mt1 = torch.tensor([[1, 2],[3, 4]])
mt2 = torch.tensor([[10, 20],[30, 40]])

print(mt1)
print(type(mt1))
print(mt1.shape)

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
torch.Size([2, 2])


In [25]:
# 브로드 캐스팅 
print(mt1 + num1)
print(mt1 + mt2)

tensor([[11, 12],
        [13, 14]])
tensor([[11, 22],
        [33, 44]])


In [26]:
# 열의 개수가 달르면 안됨 ->()
print(mt  + v1)

NameError: name 'mt' is not defined

In [27]:
# 치원은 달라도 됌 
# 차원은 달라도 상관없으나 , 열의 개수가 다르면 연산할 수 없다 
print(mt1 + torch.tensor([100, 200]))

tensor([[101, 202],
        [103, 204]])


## 4) 텐서 

In [28]:
data = [
    [1, 2], 
    [3, 4]
]
t1 = torch.tensor(data)
print(t1)

tensor([[1, 2],
        [3, 4]])


In [29]:
[1, 2] + [3, 4]
# 시퀀스 자료구조 끼리 연산 -> 시퀀스 연산자

[1, 2, 3, 4]

### tensor -> ndarray

In [30]:
print(t1)
print(type(t1), end="\n\n")
print(t1.numpy())
print(type(t1.numpy()))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


## tensor -> ndarray

In [32]:
ndarray1 = np.array([10, 20, 30])
print(ndarray1)
print(torch.from_numpy(ndarray1))

[10 20 30]
tensor([10, 20, 30])


In [37]:
t3 = torch.tensor([
    [1, 2, 3, 4],
    [10, 20, 30, 40],
    [5, 6, 7, 8]
])
print(t3)
print(t3.size())

# 인덱싱 
print(t3[1])

tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40],
        [ 5,  6,  7,  8]])
torch.Size([3, 4])
tensor([10, 20, 30, 40])


In [38]:
# 슬라이싱 
print(t1[1:2])

tensor([[3, 4]])


In [46]:
print(t3)


tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40],
        [ 5,  6,  7,  8]])


In [47]:
# 모든 행의 마지막 (차원) 열의 0번 
print(t3[:, 0])

print(t3[..., 0])

tensor([ 1, 10,  5])
tensor([ 1, 10,  5])


In [48]:
t4 = np.arange(1, 13).reshape(2, 2, 3)
t4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
# -1 : 알아서 바꿔라 
t4 = np.arange(1, 13).reshape(2, -1, 3)
t4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
t5 = torch.from_numpy(t4)
t5

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [55]:
print(t5[:, 0])

tensor([[1, 2, 3],
        [7, 8, 9]])


In [57]:
print(t5[..., 0])

tensor([[ 1,  4],
        [ 7, 10]])


## 5. 행렬곱 

## 내적(Dot Product) 계산 및 개념

### 개념
- 내적은 두 벡터 간의 원소별 곱을 모두 더하는 연산으로, 두 벡터가 얼마나 같은 방향을 향하는지 나타내는 유사도(방향성 일치도)의 척도입니다.

### 내적 공식
3차원 벡터 A = (x1, y1, z1)와 B = (x2, y2, z2)의 내적 공식은 다음과 같습니다.

A · B = x1*x2 + y1*y2 + z1*z3

- 첫 번째 성분끼리 곱하기: 1 x 11 = 11
- 두 번째 성분끼리 곱하기: 2 x 12 = 24
- 세 번째 성분끼리 곱하기: 3 x 13 = 39
- 최종 내적 값: 11 + 24 + 39 = 74 (0차원 스칼라)

### 내적과 행렬곱의 관계
1차원, 2차원, 3차원 텐서 모두 행렬곱 연산이 가능하며, 행렬곱의 결과 형태(Shape)는 입력되는 행렬들의 크기에 따라 다르게 결정됩니다. 행렬곱을 이루는 각 위치의 원소를 계산하는 본질적인 연산 방식이 바로 벡터의 내적이며, (1, n) 행렬과 (n, 1) 행렬의 곱처럼 결과가 1x1 형태의 2차원 행렬로 나오는 경우 그 내부 원소 값은 두 벡터의 내적 값(0차원 스칼라)과 동일합니다.

In [58]:
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([1, 2, 3])

print(v1)
print(v2)

tensor([1, 2, 3])
tensor([1, 2, 3])


In [59]:
print(torch.matmul(v1, v2))

tensor(14)


In [60]:
"""
    1차원 벡터 내적 [1, 2, 3] x [1, 2, 3]
    (3,) 크기를 가지는 1차원 벡터 2개의 내적 연산 과정입니다.

    - 첫 번째 성분끼리 곱하기: 1 x 1 = 1
    - 두 번째 성분끼리 곱하기: 2 x 2 = 4
    - 세 번째 성분끼리 곱하기: 3 x 3 = 9
    - 최종 연산 결과: 1 + 4 + 9 = 14
"""

None

In [ ]:
v3 = torch

## 파이토치의 핵심 장점: GPU 활용과 연산 가속
- GPU(Graphics Processing Unit)는 본래 이미지 렌더링과 같은 대규모 병렬 계산을 처리하기 위해 설계된 그래픽 처리 장치입니다.  
  하지만 최근에는 수많은 행렬 및 벡터 연산이 필요한 인공지능(AI)과 딥러닝 분야에서 뛰어난 연산 가속기로 널리 활용되고 있습니다.  
  GPU는 다수의 코어를 통해 수천, 수만 개의 연산을 동시에 병렬로 처리할 수 있는 구조를 갖추고 있어 딥러닝 모델 학습에 매우 최적화되어 있습니다.
- 파이토치에서 이러한 GPU 가속을 활용하기 위해서는 외장 그래픽카드와 함께 전용 하드웨어 설치 프로그램(예: NVIDIA CUDA 등)을 갖추어야 하며,  
  내장 그래픽 환경에서는 사용이 불가능합니다. 만약 로컬에 적합한 그래픽 카드가 없는 경우, 구글 코랩(Google Colab) 환경을 이용하면  
  무료로 GPU 가속을 사용해 볼 수 있습니다.
- 한편, 머신러닝과 딥러닝 전용으로 개발된 또 다른 가속 장치인 TPU(Tensor Processing Unit)의 경우,  
  본래 텐서플로(TensorFlow) 환경에 최적화되어 있어 파이토치에서는 직접적인 사용 및 적용이 다소 제한적입니다.  
  따라서 파이토치를 활용한 딥러닝 연산 시에는 GPU 환경을 구축하고 사용하는 것이 가장 일반적이고 효율적인 방법입니다.

In [62]:
print("Cuda 사용 가능 여부:", torch.cuda.is_available())
print("Mps 사용 가능 여부:", torch.mps.is_available())
print("Cpu 사용 가능 여부:", torch.cpu.is_available())
print("Xpu(Itel 내장 그래픽)사용가능 여부 :", torch.xpu.is_available())

Cuda 사용 가능 여부: False
Mps 사용 가능 여부: True
Cpu 사용 가능 여부: True
Xpu(Itel 내장 그래픽)사용가능 여부 : False


In [ ]:
ㅌ = torch([3.0, ])