# 판다스(Pandas)
   - 데이터 분석 라이브러리
   - 행(row), 열(column) 형태의 정형 데이터 객체를 다룬다.
   
## 2차원 데이터
   - 엑셀의 시트, RDB의 테이블과 같은 형태이다.
   - 대표적인 객체 DataFrame, Series
   
## Series
   - Pandas의 기본 객체 중 하나로, numpy의 ndarray를 기반으로 인덱싱 기능이 추가된
   1차원 배열을 나타낸다. (index x value의 형태)
   - index를 지정하지 않을 시, 기본적으로 ndarray와 같이 0-based 인덱스 생성한다
   - index를 지정할 경우 명시적으로 지정된 index를 사용한다.
   - 같은 타입의 0개 이상의 데이터를 가질 수 있다

[판다스 공식문서](https://pandas.pydata.org/)

In [2]:
import numpy as np
import pandas as pd


In [4]:
arr1 = np.array([1,2,3])
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
pd.Series(arr1)   # Series : 클래스 -> 필드 가능  

0    1
1    2
2    3
dtype: int64

In [9]:
s1 = pd.Series(arr1, index= ['a', 'b', 'c'])   # 인덱스 자리에  a', 'b', 'c'들어감 , 이는 키값 임 
s1

a    1
b    2
c    3
dtype: int64

In [11]:
print(s1['a'])

1


In [12]:
s2 = pd.Series([i * 10 for i in range(1, 6)])
s2

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [13]:
# 넘파이로 변경함 
s2[0]

np.int64(10)

## 주요 필드 
- values: pd의 해당값을 반환하는 필드
- index: pd의 index를 반환하는 필드 
- dtype: 현재 pd의 타입을 반환하는 필드 

In [15]:
s1.values

array([1, 2, 3])

In [16]:
s1.index

Index(['a', 'b', 'c'], dtype='str')

In [17]:
s1.dtype

dtype('int64')

In [ ]:
name1= ["홍길동", "장보고", "dltnstls"]
scores = [70, 80, 90]

# 값을 명시해서 넣는 것을 권장한다 
pd.Series(dfata=score
          # 딕셔너리 

In [37]:
incomes = {
    "한혜진": 1500000,
    "이상아": 50000,
    "오승현": 500000,
    "이예나": 1000000,
    "김진휘": 57000000,
    "채진성": 500000,
    "한우물": -10000
}

print(incomes.keys())
print(incomes.values())

dict_keys(['한혜진', '이상아', '오승현', '이예나', '김진휘', '채진성', '한우물'])
dict_values([1500000, 50000, 500000, 1000000, 57000000, 500000, -10000])


In [38]:
# pd.Series(data=incomes.values(), incomes = incomes.key()) 
s3 = pd.Series(incomes)

print(s3)

한혜진     1500000
이상아       50000
오승현      500000
이예나     1000000
김진휘    57000000
채진성      500000
한우물      -10000
dtype: int64


In [39]:
inco

NameError: name 'inco' is not defined

In [40]:
s3["오승현":"채진성"]

오승현      500000
이예나     1000000
김진휘    57000000
채진성      500000
dtype: int64

In [20]:
# 한혜진 수익을 -50000으로 변경 
pd.

KeyError: 0

In [41]:

s3["한혜진"] = -50000

s3

한혜진      -50000
이상아       50000
오승현      500000
이예나     1000000
김진휘    57000000
채진성      500000
한우물      -10000
dtype: int64

In [42]:
s3["이예나": "한우물"]

이예나     1000000
김진휘    57000000
채진성      500000
한우물      -10000
dtype: int64

In [43]:
print(s3["이예나"])
print(type(s3["이예나"]))

1000000
<class 'numpy.int64'>


In [44]:
print(s3[["이예나"]])
print(type(s3[["이예나"]]))

이예나    1000000
dtype: int64
<class 'pandas.Series'>


In [45]:
# 이상아 , 채진성 
s3[['이상아', '채진성']]

이상아     50000
채진성    500000
dtype: int64

In [48]:
# view만 제공 
# 원본 변경됨 - 주의 가 필요 
s3[['이상아', '채진성']] = 10, 10
s3

한혜진      -50000
이상아          10
오승현      500000
이예나     1000000
김진휘    57000000
채진성          10
한우물      -10000
dtype: int64

In [49]:
s4 = s3[['이상아', '채진성']]
s4
# 원본 보호 

이상아    10
채진성    10
dtype: int64

In [55]:
# 원본 보호 -  원본 카피 
s4 = s3.copy()
s4

한혜진      -50000
이상아          10
오승현      500000
이예나     1000000
김진휘    57000000
채진성          10
한우물      -10000
dtype: int64

In [56]:
s3

한혜진      -50000
이상아          10
오승현      500000
이예나     1000000
김진휘    57000000
채진성          10
한우물      -10000
dtype: int64

In [58]:
# Name: 수익 이라고 추가 됨 
s3.name = "수익"
# 인덱스에 이름이라고 추가 됨 
s3.index.name = "이름 "


s3

이름 
한혜진      -50000
이상아          10
오승현      500000
이예나     1000000
김진휘    57000000
채진성          10
한우물      -10000
Name: 수익, dtype: int64

## Series 함수
    - ndim : 차원 반환
    - len : 데이터 길이
    - size : 개수 반환
    - shape : 튜플의 형태로 shape반환
    - unique : 유일한 값만 udarray로 반환
    - count : NaN을 제외한 개수를 반환
    - mean : NaN를 제외한 평균
    - value_counts : NaN를 제외하고 각 값들의 빈도를 반환

## NaN(Not a Number)
- 숫자형 데이터가 들어와야되는데 숫자형 데이터가 아닌 다른 값이 들어올 떄 나타나는 값
- ex) DBMS -> null, JS -> undefind, python -> None 

In [60]:
s1 = pd.Series([10, 2, 3, 3, np.nan, 2, 3, 5, 7, 8, np.nan, np.nan])
s1


0     10.0
1      2.0
2      3.0
3      3.0
4      NaN
5      2.0
6      3.0
7      5.0
8      7.0
9      8.0
10     NaN
11     NaN
dtype: float64

In [61]:
s1.size

12

In [62]:
s1.shape 

(12,)

In [63]:
len(s1)

12

In [66]:
s1.unique()

array([10.,  2.,  3., nan,  5.,  7.,  8.])

In [67]:
s1.count()

np.int64(9)

In [69]:
# NoN 데이터가 있다 
print(s1.count())
print(len(s1))

9
12


In [ ]:
s1.value_count

In [ ]:
defou;

In [ ]:
# default : 5 - tail :  뒤에서 부터 5개 
s1.tail(3)

## 시리즈(Serise)의 연산 
- 시리즈는 시리즈끼리 연산이 가능하다. 단, index를 기준으로 연산된다
- 이 특징은 DataFrame에서도 동일하게 적용된다 

In [ ]:
products = {
    "난리부르스 치킨": 30000,
    "요아정 벌집 요거트": 50000,
    "국밥": 13000,
    
}


In [71]:
s3 = pd.Series(products2)
s3

NameError: name 'products2' is not defined

In [ ]:
s2 * 1.2 


In [72]:
# 가격이 3만원을 넘는 괘씸한 음식을 골라내기 
price_mask = s2 > 30000
s2[price_mask]

Series([], dtype: int64)

In [75]:
hobbies = {
    "승현": "칵테일방, 찜질방, 노래방",
    "예나": "요리, 노래방, 영화",
    "진성": "호프, 노래방, 호프집",
    "가나디": "그릭요거트, 그림그리기, 영화",
    "지혁": "음주, 흡연, 도박",
    "시우": "볼링, 클라이밍, 보석십자수"
}

s4 = pd.Series(hobbies)

In [79]:
# 악의 축 취미를 가진 사용자를 mask로 제거하기 (호프, 도박, 흡연)
hobbie_mask = s4 = ("호프", "도박", "흡연")
s4[hobbie_mask]

TypeError: tuple indices must be integers or slices, not tuple